# This file defines all the dependencies for each test suite. Each suite will declare their
# own dependencies (object files) so modules can be mocked/swapped easily.

TEST_BIN_DIR = bin/test
TEST_API_BIN_DIR = $(TEST_BIN_DIR)/api
TEST_INTERNAL_BIN_DIR = $(TEST_BIN_DIR)/internal
TEST_INTERNAL_ALIGNED_ALLOC_BIN_DIR = $(TEST_INTERNAL_BIN_DIR)/aligned_alloc
TEST_INTERNAL_BITSTRING_BIN_DIR = $(TEST_INTERNAL_BIN_DIR)/bitstring
TEST_INTERNAL_TWQL_PACKED_BIN_DIR = $(TEST_INTERNAL_BIN_DIR)/twql_packed
TEST_QUEUE_BIN_DIR = $(TEST_BIN_DIR)/queue
TEST_QUEUE_FIFO_BIN_DIR = $(TEST_BIN_DIR)/queue/fifo

TEST_BIN_DIRS = $(TEST_BIN_DIR) $(TEST_API_BIN_DIR) $(TEST_INTERNAL_BIN_DIR) \
		$(TEST_INTERNAL_ALIGNED_ALLOC_BIN_DIR) $(TEST_INTERNAL_BITSTRING_BIN_DIR) \
		$(TEST_INTERNAL_TWQL_PACKED_BIN_DIR) $(TEST_QUEUE_BIN_DIR) \
		$(TEST_QUEUE_FIFO_BIN_DIR)


TEST_BUILD_DIR = build/test
TEST_API_BUILD_DIR = $(TEST_BUILD_DIR)/api
TEST_INTERNAL_BUILD_DIR = $(TEST_BUILD_DIR)/internal
TEST_INTERNAL_ALIGNED_ALLOC_BUILD_DIR = $(TEST_INTERNAL_BUILD_DIR)/aligned_alloc
TEST_INTERNAL_BITSTRING_BUILD_DIR = $(TEST_INTERNAL_BUILD_DIR)/bitstring
TEST_INTERNAL_TWQL_PACKED_BUILD_DIR = $(TEST_INTERNAL_BUILD_DIR)/twql_packed
TEST_QUEUE_BUILD_DIR = $(TEST_BUILD_DIR)/queue
TEST_QUEUE_FIFO_BUILD_DIR = $(TEST_BUILD_DIR)/queue/fifo
TEST_MOCK_BUILD_DIR = $(TEST_BUILD_DIR)/mock
TEST_MOCK_ALLOC_BUILD_DIR = $(TEST_BUILD_DIR)/mock/alloc
TEST_MOCK_THREADING_BUILD_DIR = $(TEST_BUILD_DIR)/mock/threading

TEST_BUILD_DIRS = $(TEST_BUILD_DIR) $(TEST_API_BUILD_DIR) $(TEST_INTERNAL_BUILD_DIR) \
		  $(TEST_INTERNAL_ALIGNED_ALLOC_BUILD_DIR) $(TEST_INTERNAL_BITSTRING_BUILD_DIR) \
		  $(TEST_INTERNAL_TWQL_PACKED_BUILD_DIR) $(TEST_QUEUE_BUILD_DIR) $(TEST_QUEUE_FIFO_BUILD_DIR) \
		  $(TEST_MOCK_BUILD_DIR) $(TEST_MOCK_ALLOC_BUILD_DIR) $(TEST_MOCK_THREADING_BUILD_DIR)

TEST_ALL_DEPS = $(TEST_BUILD_DIR)/unity.o $(TEST_MOCK_THREADING_BUILD_DIR)/threading_trace_fault.o \
		$(TEST_MOCK_ALLOC_BUILD_DIR)/alloc_trace.o
TEST_COMMON_DEPS = $(OBJ_OUT)

# List of TESTS
TEST_QUEUE_FIFO_INIT = $(TEST_QUEUE_FIFO_BIN_DIR)/test_fifo_init
TEST_QUEUE_FIFO_INIT_MALLOC_ERROR = $(TEST_QUEUE_FIFO_BIN_DIR)/test_fifo_init_malloc_error
TEST_QUEUE_FIFO_INIT_SEM_ERROR = $(TEST_QUEUE_FIFO_BIN_DIR)/test_fifo_init_sem_error
TEST_QUEUE_FIFO_POP = $(TEST_QUEUE_FIFO_BIN_DIR)/test_fifo_pop
TEST_QUEUE_FIFO_PUSH = $(TEST_QUEUE_FIFO_BIN_DIR)/test_fifo_push

TEST_INTERNAL_ALIGNED_ALLOC = $(TEST_INTERNAL_ALIGNED_ALLOC_BIN_DIR)/test_aligned_alloc
TEST_INTERNAL_BITSTRING = $(TEST_INTERNAL_BITSTRING_BIN_DIR)/test_bitstring
TEST_INTERNAL_BITSTRING_ATOMIC = $(TEST_INTERNAL_BITSTRING_BIN_DIR)/test_bitstring_atomic
TEST_INTERNAL_TWQL_PACKED = $(TEST_INTERNAL_TWQL_PACKED_BIN_DIR)/test_twql_packed

TEST_API_CAPABILITY = $(TEST_API_BIN_DIR)/test_fiber_capability_get
TEST_API_INIT = $(TEST_API_BIN_DIR)/test_fiber_api_init
TEST_API_JOBS_PENDING = $(TEST_API_BIN_DIR)/test_fiber_api_jobs_pending
TEST_API_JOB_PUSH = $(TEST_API_BIN_DIR)/test_fiber_api_job_push
TEST_API_JOB_PUSH_RAW = $(TEST_API_BIN_DIR)/test_fiber_api_job_push_raw
TEST_API_LIBVERSION_COMPAT = $(TEST_API_BIN_DIR)/test_fiber_api_libversion_compatible

# Test queue dependencies
TEST_QUEUE_FIFO_COMMON_DEPS = $(TEST_ALL_DEPS) build/threading_pthread.o build/queue/fifo.o

$(TEST_QUEUE_FIFO_INIT)_DEPS = $(TEST_QUEUE_FIFO_COMMON_DEPS) $(TEST_QUEUE_FIFO_BUILD_DIR)/fifo_init.o

$(TEST_QUEUE_FIFO_INIT_MALLOC_ERROR)_DEPS = $(TEST_QUEUE_FIFO_COMMON_DEPS) \
	                             	    $(TEST_MOCK_ALLOC_BUILD_DIR)/alloc_fault.o \
				            $(TEST_QUEUE_FIFO_BUILD_DIR)/fifo_init_malloc_error.o

$(TEST_QUEUE_FIFO_INIT_SEM_ERROR)_DEPS = $(TEST_QUEUE_FIFO_COMMON_DEPS) \
	                                 $(TEST_QUEUE_FIFO_BUILD_DIR)/fifo_init_sem_error.o

$(TEST_QUEUE_FIFO_POP)_DEPS = $(TEST_QUEUE_FIFO_COMMON_DEPS) \
	                      $(TEST_QUEUE_FIFO_BUILD_DIR)/fifo_pop.o

$(TEST_QUEUE_FIFO_PUSH)_DEPS = $(TEST_QUEUE_FIFO_COMMON_DEPS) \
	                       $(TEST_QUEUE_FIFO_BUILD_DIR)/fifo_push.o

# Test internal dependencies

# Test aligned alloc dependencies
$(TEST_INTERNAL_ALIGNED_ALLOC)_DEPS = $(TEST_BUILD_DIR)/unity.o build/aligned_alloc.o \
	$(TEST_INTERNAL_ALIGNED_ALLOC_BUILD_DIR)/aligned_alloc.o

# Test bitstring dependencies
$(TEST_INTERNAL_BITSTRING)_DEPS = $(TEST_BUILD_DIR)/unity.o $(TEST_INTERNAL_BITSTRING_BUILD_DIR)/bitstring.o
$(TEST_INTERNAL_BITSTRING_ATOMIC)_DEPS = $(TEST_BUILD_DIR)/unity.o build/threading_pthread.o \
	$(TEST_INTERNAL_BITSTRING_BUILD_DIR)/bitstring_atomic.o

# Test twql_packed dependencies
$(TEST_INTERNAL_TWQL_PACKED)_DEPS = $(TEST_BUILD_DIR)/unity.o $(TEST_INTERNAL_TWQL_PACKED_BUILD_DIR)/twql_packed.o

# Test API dependencies
TEST_API_COMMON_DEPS = $(TEST_ALL_DEPS) $(TEST_COMMON_DEPS)

$(TEST_API_CAPABILITY)_DEPS = $(TEST_API_COMMON_DEPS) $(TEST_API_BUILD_DIR)/fiber_capability_get.o

$(TEST_API_INIT)_DEPS = $(TEST_API_COMMON_DEPS) $(TEST_API_BUILD_DIR)/fiber_init.o

$(TEST_API_JOBS_PENDING)_DEPS = $(TEST_API_COMMON_DEPS) $(TEST_API_BUILD_DIR)/fiber_jobs_pending.o

$(TEST_API_JOB_PUSH)_DEPS = $(TEST_API_COMMON_DEPS) $(TEST_API_BUILD_DIR)/fiber_job_push.o

$(TEST_API_JOB_PUSH_RAW)_DEPS = $(TEST_API_COMMON_DEPS) $(TEST_API_BUILD_DIR)/fiber_job_push_raw.o

$(TEST_API_LIBVERSION_COMPAT)_DEPS = $(TEST_ALL_DEPS) $(TEST_API_BUILD_DIR)/fiber_libversion_compatible.o \
				     $(filter-out %version.o, $(TEST_COMMON_DEPS))

TEST_QUEUE_ALL = $(TEST_QUEUE_FIFO_INIT) $(TEST_QUEUE_FIFO_INIT_MALLOC_ERROR) $(TEST_QUEUE_FIFO_INIT_SEM_ERROR) \
		 $(TEST_QUEUE_FIFO_POP) $(TEST_QUEUE_FIFO_PUSH)

TEST_INTERNAL_ALIGNED_ALLOC_ALL = $(TEST_INTERNAL_ALIGNED_ALLOC)
TEST_INTERNAL_BITSTRING_ALL = $(TEST_INTERNAL_BITSTRING_ATOMIC) $(TEST_INTERNAL_BITSTRING)
TEST_INTERNAL_TWQL_ALL = $(TEST_INTERNAL_TWQL_PACKED)

TEST_INTERNAL_ALL = $(TEST_INTERNAL_ALIGNED_ALLOC_ALL) $(TEST_INTERNAL_BITSTRING_ALL) $(TEST_INTERNAL_TWQL_ALL)

TEST_API_ALL   = $(TEST_API_CAPABILITY) $(TEST_API_INIT) $(TEST_API_JOBS_PENDING) $(TEST_API_JOB_PUSH) \
		 $(TEST_API_JOB_PUSH_RAW) $(TEST_API_LIBVERSION_COMPAT)

TEST_ALL = $(TEST_QUEUE_ALL) $(TEST_INTERNAL_ALL) $(TEST_API_ALL)
